POST http://localhost:3000/api/auth/register/
Content-Type: application/json

{
    "name": "PETEr",
    "email": "PEEr@utad.com",
    "password": "password",
    "age": 22,
    "city": "madrid",
    "accept": true,
    "interests": ["cars"],
    "role": "user"
}

###

POST http://localhost:3000/api/auth/login/
Content-Type: application/json

{
    "email": "danie@utad.com",
    "password": "password"
}

###











GET http://localhost:3000/api/user/

###

GET http://localhost:3000/api/user/6435458e46a405a819d0901c

###

POST http://localhost:3000/api/user/ HTTP/1.1
Content-Type: application/json

{
    "name": "Dani",
    "email": "pepi@utad.com",
    "password": "password",
    "age": 22,
    "city": "madrid",
    "accept": true,
    "interests": ["cars"],
    "role": "user"
}

###

PUT http://localhost:3000/api/user/6435458e46a405a819d0901c HTTP/1.1
Content-Type: application/json

{
    "name": "Alexander",
    "email": "pelo@utad.com",
    "password": "password",
    "age": 22,
    "city": "madrid",
    "accept": true,
    "interests": ["cars", "basket"],
    "role": "user"
}

###

DELETE http://localhost:3000/api/user/6435458e46a405a819d0901c HTTP/1.1

###

GET http://localhost:3000/api/user/search/madrid HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM2ZWZlMTQ0ODVkZDEzMDBhNjM3ZTciLCJpYXQiOjE2ODI1MDE1ODV9.OgEmZ1UMvGnAgqyxyYkN8-MW-rGEVF08ugTj2K33Upk





###






###SOLO SIENDO ADMIN TENEMOS ACCESO A LAS PETICIONES DE LOS COMERCIOS

GET http://localhost:3000/api/commerce/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ4MDk2MTllM2RkYmY0ZjhkMjI0MmMiLCJpYXQiOjE2ODI0NDI2MjQsImV4cCI6MTY4MjQ0OTgyNH0.XVs4iRxOeP7FBd05OIG_Sc93Br8yE8RKc5dLF-9JsUc

###

GET http://localhost:3000/api/commerce/6436efe14485dd1300a637e7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ4MDk2MTllM2RkYmY0ZjhkMjI0MmMiLCJpYXQiOjE2ODI0NDI2MjQsImV4cCI6MTY4MjQ0OTgyNH0.XVs4iRxOeP7FBd05OIG_Sc93Br8yE8RKc5dLF-9JsUc

###

POST http://localhost:3000/api/commerce/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ4MDk2MTllM2RkYmY0ZjhkMjI0MmMiLCJpYXQiOjE2ODI0NDI2MjQsImV4cCI6MTY4MjQ0OTgyNH0.XVs4iRxOeP7FBd05OIG_Sc93Br8yE8RKc5dLF-9JsUc

{
    "name": "Comercio 2345",
    "CIF": "22345347H",
    "email": "comercio2345@email.com",
    "direction": "calle Comercio numero 3",
    "phone": 567345723,
    "mediaId": "0123456789abcdef01234564"
}

###

PUT http://localhost:3000/api/commerce/6446ae92a50706b9e97e3b8e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDNlNjAyZTFjMmVmODFhNTJiMThhOGYiLCJpYXQiOjE2ODIzNTM0NjIsImV4cCI6MTY4MjM2MDY2Mn0.TTXJ4FK-2lO8j2B6ZkFKTPv8Q-z_n1hSXDQriSQyE8s
Content-Type: application/json

{
    "name": "Comercio 15",
    "CIF": "22375693H",
    "email": "comercio15@email.com",
    "direction": "calle Comercio numero 3",
    "phone": 567345723,
    "mediaId": "0123456789abcdef01234564"
}

###

DELETE http://localhost:3000/api/commerce/6436efb74485dd1300a637db HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDNlNjAyZTFjMmVmODFhNTJiMThhOGYiLCJpYXQiOjE2ODIzNTM0NjIsImV4cCI6MTY4MjM2MDY2Mn0.TTXJ4FK-2lO8j2B6ZkFKTPv8Q-z_n1hSXDQriSQyE8s
Content-Type: application/json






###

POST http://localhost:3000/api/auth/login/commerce
Content-Type: application/json

{
    "name": "Comercio 2"
}

###

POST http://localhost:3000/api/web/photos/6436efe14485dd1300a637e7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM2ZWZlMTQ0ODVkZDEzMDBhNjM3ZTciLCJpYXQiOjE2ODI0OTU0MDB9.XS2Scyrz11WEAstA8xIIchGscPIgYfcgoeg2d4HhlMg
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="farmacia_fachada_013.jpg"
Content-Type: image/jpg

< ./farmacia_fachada_013.jpg
--Boundry--

###


GET http://localhost:3000/api/web/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM2ZWZlMTQ0ODVkZDEzMDBhNjM3ZTciLCJpYXQiOjE2ODI0MTM4MDEsImV4cCI6MTY4MjQyMTAwMX0.teyjW4IcWbCC_BATDl_L90EsUFeB1XS6PlYax-bh5PU

###

GET http://localhost:3000/api/web/6436f3bc91303f93a0ac109e





### ACCESO A WEBS EN FUNCION DE SU CIUDAD Y/O ACTIVIDAD

GET http://localhost:3000/api/web/search/Madrid

###

###
GET http://localhost:3000/api/web/search/Madrid/futbol

###


POST http://localhost:3000/api/web/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM2ZWZlMTQ0ODVkZDEzMDBhNjM3ZTciLCJpYXQiOjE2ODI0NDY0NjF9.YN2zU1NdDEfQchM3TfH0TpcJVFQ6Tp6p0B7F0mYnzoc

{
    "city": "Madrid",
    "activity": "sport",
    "title": "Futbol web",
    "resume": "Esto es una web"
}

###

PUT http://localhost:3000/api/web/6436efe14485dd1300a637e7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM2ZWZlMTQ0ODVkZDEzMDBhNjM3ZTciLCJpYXQiOjE2ODI0MTM4OTcsImV4cCI6MTY4MjQyMTA5N30.BH8EmFgJEMXmdzglEcUPdqvyxPN_0l0uTkWvYRaZAxw

{
    "city": "Web 1",
    "activity": "futbol y cine",
    "title": "Futbol web",
    "resume": "Esto es una web"
}

###

DELETE http://localhost:3000/api/web/6436efe14485dd1300a637e7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM2ZWZlMTQ0ODVkZDEzMDBhNjM3ZTciLCJpYXQiOjE2ODI0NDY5MTR9.Fn5TX9ZomV-ZdBJgs5SYVxusIIuYHiU_pGF5apvYBy8

###

POST http://localhost:3000/api/web/texts/6436efe14485dd1300a637e7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM2ZWZlMTQ0ODVkZDEzMDBhNjM3ZTciLCJpYXQiOjE2ODI0NDY5MTR9.Fn5TX9ZomV-ZdBJgs5SYVxusIIuYHiU_pGF5apvYBy8
Content-Type: application/json

{
    "texts": "Primer texto de la web"
}

###

PATCH http://localhost:3000/api/web/6436efe14485dd1300a637e7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ4MDk2MTllM2RkYmY0ZjhkMjI0MmMiLCJpYXQiOjE2ODI1MjI3OTAsImV4cCI6MTY4MjUyOTk5MH0.ponRLq9fygVfn64jpRRbao_FDu1PSbpxyX6mQ3tRXNc
Content-Type: application/json

{
    "score": 8,
    "review": "Second web Review"
}