POSt http://localhost:3000/api/auth/register/
Content-Type: application/json

{
    "name": "Pepe",
    "email": "pepe@utad.com",
    "password": "password",
    "age": 22,
    "city": "madrid",
    "accept": true,
    "interests": ["cars", "basket"],
    "role": "user"
}

###

POSt http://localhost:3000/api/auth/login/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDNlNjAyZTFjMmVmODFhNTJiMThhOGYiLCJpYXQiOjE2ODE4MDk0NTQsImV4cCI6MTY4MTgxNjY1NH0.oMpwaNpEBCKLz6pcqsh9bis6rhc8Gq4zCq1wH0row5I

{
    "email": "pepe@utad.com",
    "password": "password"
}

###











GET http://localhost:3000/api/user/

###

GET http://localhost:3000/api/user/6435458e46a405a819d0901c

###

POST http://localhost:3000/api/user/ HTTP/1.1
Content-Type: application/json

{
    "name": "Dani",
    "email": "pepi@utad.com",
    "password": "password",
    "age": 22,
    "city": "madrid",
    "accept": true,
    "interests": ["cars", "basket"],
    "role": "user"
}

###

PUT http://localhost:3000/api/user/6435458e46a405a819d0901c HTTP/1.1
Content-Type: application/json

{
    "name": "Alexander",
    "email": "pelo@utad.com",
    "password": "password",
    "age": 22,
    "city": "madrid",
    "accept": true,
    "interests": ["cars", "basket"],
    "role": "user"
}

###

DELETE http://localhost:3000/api/user/6435458e46a405a819d0901c HTTP/1.1





###






###SOLO SIENDO ADMIN TENEMOS ACCESO A LAS PETICIONES DE LOS COMERCIOS

GET http://localhost:3000/api/commerce/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDNlNjAyZTFjMmVmODFhNTJiMThhOGYiLCJpYXQiOjE2ODIzNTM0NjIsImV4cCI6MTY4MjM2MDY2Mn0.TTXJ4FK-2lO8j2B6ZkFKTPv8Q-z_n1hSXDQriSQyE8s

###

GET http://localhost:3000/api/commerce/6436efe14485dd1300a637e7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDNlNjAyZTFjMmVmODFhNTJiMThhOGYiLCJpYXQiOjE2ODIzNTM0NjIsImV4cCI6MTY4MjM2MDY2Mn0.TTXJ4FK-2lO8j2B6ZkFKTPv8Q-z_n1hSXDQriSQyE8s

###

POST http://localhost:3000/api/commerce/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDNlNjAyZTFjMmVmODFhNTJiMThhOGYiLCJpYXQiOjE2ODIzNTM0NjIsImV4cCI6MTY4MjM2MDY2Mn0.TTXJ4FK-2lO8j2B6ZkFKTPv8Q-z_n1hSXDQriSQyE8s

{
    "name": "Comercio 10",
    "CIF": "22355693H",
    "email": "comercio10@email.com",
    "direction": "calle Comercio numero 3",
    "phone": 567345523,
    "mediaId": "0123456789abcdef01234568"
}

###

PUT http://localhost:3000/api/commerce/6446ae92a50706b9e97e3b8e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDNlNjAyZTFjMmVmODFhNTJiMThhOGYiLCJpYXQiOjE2ODIzNTM0NjIsImV4cCI6MTY4MjM2MDY2Mn0.TTXJ4FK-2lO8j2B6ZkFKTPv8Q-z_n1hSXDQriSQyE8s
Content-Type: application/json

{
    "name": "Comercio 10",
    "CIF": "22355693H",
    "email": "comercio10@email.com",
    "direction": "calle Comercio numero 3",
    "phone": 567345723,
    "mediaId": "0123456789abcdef01234564"
}

###

DELETE http://localhost:3000/api/commerce/6436efb74485dd1300a637db HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDNlNjAyZTFjMmVmODFhNTJiMThhOGYiLCJpYXQiOjE2ODIzNTM0NjIsImV4cCI6MTY4MjM2MDY2Mn0.TTXJ4FK-2lO8j2B6ZkFKTPv8Q-z_n1hSXDQriSQyE8s
Content-Type: application/json






###

POST http://localhost:3000/api/auth/login/commerce
Content-Type: application/json

{
    "name": "Comercio 2"
}

###


GET http://localhost:3000/api/web/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM2ZWZlMTQ0ODVkZDEzMDBhNjM3ZTciLCJpYXQiOjE2ODI0MTM4MDEsImV4cCI6MTY4MjQyMTAwMX0.teyjW4IcWbCC_BATDl_L90EsUFeB1XS6PlYax-bh5PU

###

GET http://localhost:3000/api/web/6436f3bc91303f93a0ac109e





### ACCESO A WEBS EN FUNCION DE SU CIUDAD Y/O ACTIVIDAD

GET http://localhost:3000/api/web/search/Madrid

###

###
GET http://localhost:3000/api/web/search/Madrid/futbol

###


POST http://localhost:3000/api/web/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM2ZWZlMTQ0ODVkZDEzMDBhNjM3ZTciLCJpYXQiOjE2ODI0MTM4MDEsImV4cCI6MTY4MjQyMTAwMX0.teyjW4IcWbCC_BATDl_L90EsUFeB1XS6PlYax-bh5PU

{
    "city": "Madrid",
    "activity": "basket",
    "title": "Futbol web",
    "resume": "Esto es una web"
}

###

PUT http://localhost:3000/api/web/6436efe14485dd1300a637e7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM2ZWZlMTQ0ODVkZDEzMDBhNjM3ZTciLCJpYXQiOjE2ODI0MTM4OTcsImV4cCI6MTY4MjQyMTA5N30.BH8EmFgJEMXmdzglEcUPdqvyxPN_0l0uTkWvYRaZAxw

{
    "city": "Web 1",
    "activity": "futbol y cine",
    "title": "Futbol web",
    "resume": "Esto es una web"
}

###

DELETE http://localhost:3000/api/web/6436efe14485dd1300a637e7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM2ZWZlMTQ0ODVkZDEzMDBhNjM3ZTciLCJpYXQiOjE2ODI0MTM4OTcsImV4cCI6MTY4MjQyMTA5N30.BH8EmFgJEMXmdzglEcUPdqvyxPN_0l0uTkWvYRaZAxw
